### ISSUE TITLE
ADD option title alignment

### ISSUE THREAD

**Issue by allanlaal** [tylercal/simple-titles#2]
currently seems to align to center, but left & right would also be appreciated :)

**Comment by tylercal** [comment]
because the hooks into the IDE only let you return a string, I don't think there is an easy and consistent way to change the title alignment. You *could* pad the start of the Project Format with whitespace to push the title to the right, e.g. 
```
								{DEFAULT}
```
I looked around to see if there was somewhere to hook into the way that title is rendered, but didn't have any luck. But I'm totally open to the feature if someone has a PR or an idea of how to hook in.

**Comment by allanlaal** [comment]
so currently showing the title in the middle is not from your plugin? :)

**Comment by tylercal** [comment]
That is correct, it only customizes the string content of the project and file names. Maybe something else is affecting the alignment without the plug-in? Can you share a screenshot of the differences with simple titles on and off?

**Comment by allanlaal** [comment]
lol, n00b moment here. this title centering is from my window manager :D
